[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3002
  framework = "vite"

[[redirects]]
  from = "/cloudinary-proxy/*"
  to = "https://res.cloudinary.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
